test.o: test.c ../include/simple_json.h ../include/simple_json_list.h \
 ../include/simple_json_array.h ../include/simple_json_value.h \
 ../include/simple_json_string.h ../include/simple_json_object.h \
 ../include/simple_json_error.h
